---
title: "Project 1"
author: "Sirish"
date: "2022-10-03"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(MASS)
library(dplyr)
library(readxl)
library(ggpubr)
Data <- read.csv("diamonds4.csv", header= T)
Data$clarity <- factor(Data$clarity, levels = c("SI1", "SI2", "VS1", "VS2", "VVS1", "VVS2", "IF", "FL"))
Data$color <- factor(Data$color, levels = c("J", "I", "H", "G", "F", "E", "D"))
Data$cut <- factor(Data$cut, levels = c("Good", "Very Good", "Ideal", "Astor Ideal"))
```


```{r}
ggplot(Data, aes(x=log(carat), y=log(price)))+
  geom_point()+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat")+
  geom_smooth(method="lm", col="black")
result <- lm(price~carat, Data)
Data$yhat<-result$fitted.values
Data$res<-result$residuals
ggplot(Data, aes(x=yhat,y=res))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted y", y="Residuals", title="Residual Plot")
```


```{r}
ggplot(Data, aes(x= clarity, y=log(price)))+
  geom_point()+
  labs(x= "clarity",
       y= "Price",
       title = "Price Vs Clarity")
```

```{r}
ggplot(Data, aes(x= color, y=log(price)))+
  geom_point()+
  labs(x= "Color",
       y= "Price",
       title = "Price Vs Color")
```

```{r}
ggplot(Data, aes(x= cut, y=log(price)))+
  geom_point()+
  labs(x= "cut",
       y= "Price",
       title = "Price Vs Cut")
```





```{r}
ggplot(Data, aes(x= cut, y=carat))+
  geom_point()+
  labs(x= "cut",
       y= "Carat",
       title = "Carat Vs Cut")
ggplot(Data, aes(x=log(carat), y=log(price), color = cut))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut")
#Carat vs Cut is really low when you get to Astor Ideal. Even though that Astor Ideal is what Astor specifically crafted to be the most ideal to let the light through, it seems to have a lower Carat amount. However, even though the average and median weight for the Astor diamonds are lower than the other variables, when you add price back in as a variable, you tend to see higher prices, except at the complete top. I think that this is because when making the 'most ideal cut to allow light reflection' that Astor diamonds probably had more of the original diamond cut off it. What is also interesting is that when you get to high Price and Carats and Cuts, that the Astor Ideal doesn't trend higher than the Ideal Cuts and Good cuts go above the Very Good cuts.
```


```{r}
ggplot(Data, aes(x= color, y=carat))+
  geom_point()+
  labs(x= "Color",
       y= "Carat",
       title = "Carat Vs Color")
```

```{r}
ggplot(Data, aes(x= clarity, y=carat))+
  geom_point()+
  labs(x= "Clarity",
       y= "Carat",
       title = "Carat Vs Clarity")
ggplot(Data, aes(x=log(carat), y=log(price), color = clarity))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Clarity")
#What is surprising about this is that The general price trend tends to be higher in FL, however the Carats look to be on the lower side. The higher you go in the categorical variables with Clarity, the overall Carats tend to go down. However, when price is added back as a variable, there is still an upward trend with pricing. This could be because when there is a lower clarity the weight itself is increased as to raise the price to be more of a desirable rock.
```

```{r}
Data$cut <- factor(Data$cut, levels = c("Good", "Very Good", "Ideal", "Astor Ideal"))
ggplot(Data, aes(x=log(carat), y=log(price)))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat")
ggplot(Data, aes(x=log(carat), y=log(price), color = cut))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut")

ggplot(Data, aes(x=log(carat), y=log(price), color = clarity))+
  geom_point()+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Clarity")+
  geom_smooth(method="lm", se=F)
ggplot(Data, aes(x=log(carat), y=log(price), color = color))+
  geom_point()+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Color")+
  geom_smooth(method="lm", se=F)
ggplot(Data, aes(x=log(carat), y=log(price), color = clarity, shape = cut))+
  geom_point()+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut vs Clarity")
ggplot(Data, aes(x=log(carat), y=log(price), color = color, shape = cut))+
  geom_point()+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut vs Color")
#ggplot(Data, aes(x=log(carat), y=log(price), shape = color, color = clarity))+
  #geom_point()+
  #labs(x= "Carat",
  #     y= "Price",
  #     title = "Price Vs Carat vs Cut vs Clarity")
# bad because I can't show all the data points

ggplot(Data, aes(x=log(carat), y=log(price), shape = cut, color = color))+
  geom_point()+
  facet_wrap(vars(clarity))+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut vs Color vs Clarity")


```

```{r}

ggplot(Data, aes(x=(carat),  y=(price), color = cut))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Cut")+
  stat_regline_equation()
ggplot(Data, aes(x=(carat), y=(price), color = color))+
  geom_smooth(method = lm, se=F)+
  labs(x= "Carat",
       y= "Price",
       title = "Price Vs Carat vs Color")+
  stat_regline_equation()
#From these 2 graphs we can see that for Astor Ideal and D color, that Astor Ideal starts at a higher base number (-10000), however increases at a slower rate than compared to the D color.We can also see that at the lowest Astor Ideal (Good), it starts off at a lower starting point, however increases a lot faster. What's also interesting is that the good cuts increase past all the other cuts 
```





```{r}

ggplot(Data)+
  aes(x=clarity)+
  geom_bar(fill="blue",color="orange")+    
  labs(title = "Distributions of Clarity") +
    theme(
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 0)
    )

```

```{r}

ggplot(Data)+
  aes(x=cut)+
  geom_bar(fill="blue",color="orange")+
  labs(title = "Distributions of Cut") +
  theme(
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(angle = 0)
    )
```

```{r}

ggplot(Data)+
  aes(x=color)+
  geom_bar(fill="blue",color="orange")+
  labs(title = "Distributions of Color") +
  theme(
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(angle = 0)
    )
```


```{r}
Data <- Data %>% 
  mutate(logprice = log(price))
hist(Data$logprice, 
     col="blue",
     prob = TRUE,
     xlab = "LogPrice",
     main = "Histogram and Density plot of LogPrice")
lines(density(Data$logprice),
      lwd = 2,
      col = "orange")
```